### ISSUE TITLE
Doesn't actually define minor mode

### ISSUE THREAD

**Issue by alphapapa** [stardiviner/flycheck-inline#2]
Hi there,

I was looking forward to trying this, but it's not working.  The readme says to turn on the minor mode, but looking at the code, there isn't a minor mode, just a function to turn it on.  D:

**Comment by stardiviner** [comment]
@alphapapa Hi, sorry for this, MELPA maintainer suggest me to remove that minor mode. That is an enable function. You can check out the source code. I will update the README. Thanks
